# training/export_c.py
# Exports AMCNet weights to a C header (inference/nn_weights.h).
# Run once after training: python export_c.py --weights ../model/best.pth
import argparse
import numpy as np
import torch
from model import AMCNet
from simulate import CLASSES

EPS = 1e-5  # BatchNorm epsilon (PyTorch default)


def arr(name, data, comment=''):
    flat = np.asarray(data, dtype=np.float32).flatten()
    vals = ',\n    '.join(
        ', '.join(f'{v:.8e}f' for v in flat[i:i+8])
        for i in range(0, len(flat), 8)
    )
    cmt = f'  /* {comment} */' if comment else ''
    return f'/* {name}  [{len(flat)}] */{cmt}\n' \
           f'static const float {name}[{len(flat)}] = {{\n    {vals}\n}};\n\n'


def export(weights_path, out_path):
    model = AMCNet(num_classes=len(CLASSES))
    model.load_state_dict(torch.load(weights_path, map_location='cpu',
                                     weights_only=False))
    model.eval()
    sd = {k: v.numpy() for k, v in model.state_dict().items()}

    lines = [
        '/* nn_weights.h — AUTO-GENERATED by export_c.py. DO NOT EDIT. */',
        '#ifndef NN_WEIGHTS_H',
        '#define NN_WEIGHTS_H',
        '',
        f'#define AMC_NUM_CLASSES {len(CLASSES)}',
        '',
        'static const char * const AMC_CLASS_NAMES[AMC_NUM_CLASSES] = {',
    ]
    lines += [f'    "{c}",' for c in CLASSES]
    lines += ['};', '']

    # Conv+BN layers: pre-fold BN into scale/shift for fast inference
    # scale[c] = gamma / sqrt(var + eps)
    # shift[c] = beta - mean * scale
    layer_specs = [
        # (conv_w_key, conv_b_key, bn_prefix, label)
        ('features.0.weight',  'features.0.bias',
         'features.1',  'L0'),
        ('features.4.weight',  'features.4.bias',
         'features.5',  'L1'),
        ('features.8.weight',  'features.8.bias',
         'features.9',  'L2'),
        ('features.12.weight', 'features.12.bias',
         'features.13', 'L3'),
    ]

    for cw, cb, bn, lbl in layer_specs:
        gamma = sd[f'{bn}.weight']
        beta  = sd[f'{bn}.bias']
        mean  = sd[f'{bn}.running_mean']
        var   = sd[f'{bn}.running_var']
        scale = gamma / np.sqrt(var + EPS)
        shift = beta - mean * scale

        lines.append(arr(f'{lbl}_CONV_W', sd[cw],
                         f'shape {sd[cw].shape}'))
        lines.append(arr(f'{lbl}_CONV_B', sd[cb]))
        lines.append(arr(f'{lbl}_BN_SCALE', scale, 'gamma/sqrt(var+eps)'))
        lines.append(arr(f'{lbl}_BN_SHIFT', shift, 'beta - mean*scale'))

    # Fully-connected layers
    lines.append(arr('FC0_W', sd['classifier.0.weight'],
                     f'shape {sd["classifier.0.weight"].shape}'))
    lines.append(arr('FC0_B', sd['classifier.0.bias']))
    lines.append(arr('FC1_W', sd['classifier.2.weight'],
                     f'shape {sd["classifier.2.weight"].shape}'))
    lines.append(arr('FC1_B', sd['classifier.2.bias']))

    lines.append('#endif /* NN_WEIGHTS_H */')

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'Written: {out_path}')
    print(f'  Classes : {len(CLASSES)}')
    total = sum(np.asarray(v).size for v in sd.values())
    print(f'  Params  : {total:,} floats  ({total*4/1024:.0f} KB)')


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('--weights', default='../model/best.pth')
    p.add_argument('--out',     default='../inference/nn_weights.h')
    args = p.parse_args()
    export(args.weights, args.out)
