#!/usr/bin/env python3
"""
detection/check_formats.py
Inspect the binary files generated by build_dma_stream_dataset() and
verify conversion results. Run from project root.

Usage:
    python detection/check_formats.py --src_dir ./test --dst_dir ./test_c
"""
import argparse
import os
import numpy as np

NB_N_POINTS = 2048
WB_BINS_PER_CH = 4096
WB_N_CH = 8


def inspect_wb(path: str, label: str):
    data = np.fromfile(path, dtype=np.int16)
    expected = WB_BINS_PER_CH * (WB_N_CH * 2)  # 4096 * 16 int16 = 4096 * 32 bytes
    print(f"\n[WB] {label}")
    print(f"  Size     : {os.path.getsize(path)} bytes  (expected {WB_BINS_PER_CH*32})")
    print(f"  int16 cnt: {len(data)}  (expected {expected})")

    # Reshape: (4096 bins, 8 I + 8 Q) = (4096, 16)
    mat = data.reshape(WB_BINS_PER_CH, WB_N_CH * 2)
    i_ch = mat[:, :WB_N_CH]   # I channels (int16)
    q_ch = mat[:, WB_N_CH:]   # Q channels (int16)

    power = (i_ch.astype(np.float32) / 32768)**2 + (q_ch.astype(np.float32) / 32768)**2

    # Flatten to 32768 global bins (ch * 4096 + local_bin)
    power_global = np.zeros(WB_N_CH * WB_BINS_PER_CH, dtype=np.float32)
    for ch in range(WB_N_CH):
        power_global[ch * WB_BINS_PER_CH:(ch + 1) * WB_BINS_PER_CH] = power[:, ch]

    peak_bin = int(np.argmax(power_global))
    peak_pwr = power_global[peak_bin]
    noise    = np.percentile(power_global, 30)

    print(f"  Peak bin : {peak_bin}  (center={WB_N_CH*WB_BINS_PER_CH//2})")
    print(f"  Peak pwr : {10*np.log10(peak_pwr/2+1e-30):.1f} dBFS")
    print(f"  Noise p30: {10*np.log10(noise/2+1e-30):.1f} dBFS")
    print(f"  SNR est  : {10*np.log10(peak_pwr/max(noise,1e-20)):.1f} dB")


def inspect_nb(path: str, label: str, fmt: str = 'int16'):
    print(f"\n[NB] {label}  (fmt={fmt})")
    if fmt == 'float32':
        data = np.fromfile(path, dtype=np.float32)
        print(f"  Size    : {os.path.getsize(path)} bytes  (expected {NB_N_POINTS*2*4})")
        i_vals = data[0::2]
        q_vals = data[1::2]
        print(f"  I range : [{i_vals.min():.1f}, {i_vals.max():.1f}]")
        print(f"  Q range : [{q_vals.min():.1f}, {q_vals.max():.1f}]  (should be 0)")
        power  = i_vals**2 / (i_vals.max()**2 + 1e-10)
        pk_bin = int(np.argmax(power))
        print(f"  Peak bin: {pk_bin}  (center={NB_N_POINTS//2})")
    else:
        data = np.fromfile(path, dtype=np.int16)
        print(f"  Size    : {os.path.getsize(path)} bytes  (expected {NB_N_POINTS*2*2})")
        i_vals = (data[0::2].astype(np.float32)) / 32768
        q_vals = (data[1::2].astype(np.float32)) / 32768
        power  = i_vals**2 + q_vals**2
        pk_bin = int(np.argmax(power))
        noise  = float(np.percentile(power, 30))
        pk_pwr = float(power[pk_bin])
        print(f"  I range : [{i_vals.min():.4f}, {i_vals.max():.4f}]")
        print(f"  Q range : [{q_vals.min():.4f}, {q_vals.max():.4f}]")
        print(f"  Peak bin: {pk_bin}  (center={NB_N_POINTS//2})")
        print(f"  Peak pwr: {10*np.log10(pk_pwr/2+1e-30):.1f} dBFS")
        print(f"  SNR est : {10*np.log10(pk_pwr/max(noise,1e-20)):.1f} dB")


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--src_dir', default='./test',   help='Python-generated files')
    p.add_argument('--dst_dir', default='./test_c', help='Converted C-compatible files')
    args = p.parse_args()

    # Pick one WB and one NB file for inspection
    src_wb = src_nb = dst_wb = dst_nb = None
    for fname in sorted(os.listdir(args.src_dir)):
        if fname.startswith('WB_') and src_wb is None:
            src_wb = os.path.join(args.src_dir, fname)
            dst_wb = os.path.join(args.dst_dir, fname)
        if fname.startswith('NB_') and src_nb is None:
            src_nb = os.path.join(args.src_dir, fname)
            dst_nb = os.path.join(args.dst_dir, fname)

    if src_wb:
        inspect_wb(src_wb, f'src: {os.path.basename(src_wb)}')
    if dst_wb and os.path.exists(dst_wb):
        inspect_wb(dst_wb, f'dst: {os.path.basename(dst_wb)}')

    if src_nb:
        inspect_nb(src_nb, f'src: {os.path.basename(src_nb)}', fmt='float32')
    if dst_nb and os.path.exists(dst_nb):
        inspect_nb(dst_nb, f'dst: {os.path.basename(dst_nb)}', fmt='int16')


if __name__ == '__main__':
    main()
