#!/usr/bin/env python3
"""
detection/convert_testdata.py

Converts the hardware DMA test files generated by build_dma_stream_dataset()
into the binary formats expected by our C detection code.

  WB  : 128 KB, 4096 × [I_ch0..7(int16 Q15), Q_ch0..7(int16 Q15)]
        Python uses uint16 power values in I, Q=0.  Values are 0-32767
        so the bit pattern is already valid int16 — kept as-is.
        ⚠ All signals are placed at the global center bin (single bin),
          which means WB detection will always find one signal at RF center.

  NB  : 8 KB, 2048 × [I(int16 Q15), Q(int16 Q15)] interleaved
        Python writes float32 [power_val, 0.0, power_val, 0.0, ...].
        We normalize to Q15 range and repack as int16.

  IQ  : time-domain float32 interleaved [I0,Q0,I1,Q1,...] at 1.92 Msps
        Already correct format for AMC inference path — kept as-is.
        ⚠ Resampled from hardcoded 9600 Hz; for accurate AMC testing
          use the Python training pipeline (simulate.py) instead.

Usage:
    python detection/convert_testdata.py --src_dir ./test --dst_dir ./test_c
"""
import argparse
import os
import struct
import numpy as np

NB_N_POINTS = 2048
INT16_MAX   = 32767


def convert_nb_file(src_path: str, dst_path: str):
    """
    Read NB float32 file  → write NB int16 Q15 interleaved file.

    Source layout : float32 [I0, 0.0, I1, 0.0, ...] (4 bytes × 2 × 2048 = 16 KB)
    Dest   layout : int16   [I0, Q0, I1, Q1, ...]    (2 bytes × 2 × 2048 =  8 KB)
    """
    raw = np.fromfile(src_path, dtype=np.float32)
    if len(raw) != NB_N_POINTS * 2:
        raise ValueError(f"{src_path}: expected {NB_N_POINTS*2} float32, got {len(raw)}")

    # I values are at even indices (0,2,4,...), Q=0 at odd indices
    i_vals = raw[0::2].astype(np.float32)   # 0 … ~255 range
    q_vals = raw[1::2].astype(np.float32)   # all 0.0

    # Normalize I to [-1, +1] (power values are always positive, so max maps to ~1)
    max_val = i_vals.max()
    if max_val > 0:
        i_norm = i_vals / max_val
    else:
        i_norm = i_vals

    i_q15 = np.clip(i_norm * INT16_MAX, -INT16_MAX, INT16_MAX).astype(np.int16)
    q_q15 = np.zeros(NB_N_POINTS, dtype=np.int16)

    # Interleave [I0, Q0, I1, Q1, ...]
    out = np.empty(NB_N_POINTS * 2, dtype=np.int16)
    out[0::2] = i_q15
    out[1::2] = q_q15

    out.tofile(dst_path)


def check_wb_file(src_path: str) -> bool:
    """
    WB file uses uint16 in I channel, Q=0.
    Since values are 0-32767, bit pattern is valid int16 — just copy.
    Prints a warning because all signals land at the global center bin.
    """
    size = os.path.getsize(src_path)
    expected = 4096 * 32
    if size != expected:
        print(f"  [WARN] {src_path}: size={size}, expected {expected}")
        return False
    return True


def copy_wb_file(src_path: str, dst_path: str):
    """WB is already usable as-is (uint16 values fit in int16 positive range)."""
    data = np.fromfile(src_path, dtype=np.uint8)
    data.tofile(dst_path)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--src_dir', required=True, help='Directory with Python-generated test files')
    p.add_argument('--dst_dir', required=True, help='Output directory for C-compatible files')
    args = p.parse_args()

    os.makedirs(args.dst_dir, exist_ok=True)

    nb_ok = wb_ok = iq_ok = 0
    nb_err = wb_err = 0

    for fname in sorted(os.listdir(args.src_dir)):
        src = os.path.join(args.src_dir, fname)
        dst = os.path.join(args.dst_dir, fname)

        if fname.startswith('NB_'):
            try:
                convert_nb_file(src, dst)
                nb_ok += 1
            except Exception as e:
                print(f"  [ERR] {fname}: {e}")
                nb_err += 1

        elif fname.startswith('WB_'):
            if check_wb_file(src):
                copy_wb_file(src, dst)
                wb_ok += 1
            else:
                wb_err += 1

        elif fname.startswith('IQ_'):
            # float32 interleaved time-domain IQ — copy unchanged
            import shutil
            shutil.copy2(src, dst)
            iq_ok += 1

    print(f"\nDone.")
    print(f"  WB  : {wb_ok} copied  ({wb_err} errors)")
    print(f"  NB  : {nb_ok} converted float32→int16 Q15  ({nb_err} errors)")
    print(f"  IQ  : {iq_ok} copied (time-domain, unchanged)")

    print("""
Known limitations of these test files:
  1. WB  — Signal always at global center bin (1 bin wide, 18.75 kHz).
           Detection will find ONE signal at RF center regardless of modulation.
           For multi-signal / off-center tests use sim_detect.py instead.
  2. NB  — Q channel is always 0 (power-spectrum style, not complex FFT).
           Detection works; power_dbfs values are approximate.
  3. IQ  — Resampled from hardcoded 9600 Hz; symbol timing may be wrong
           for non-2400 Bd modulations. Use training/simulate.py for
           accurate AMC inference testing.
""")


if __name__ == '__main__':
    main()
