/* detection/detection.h
 *
 * DMA data formats:
 *
 *   WB DMA (128 KB): matches Python build_dma_stream_dataset()
 *     4096 bins × [I_ch0..7 (uint16, linear power), Q_ch0..7 (uint16, 0)]
 *
 *   NB DMA (8 KB): complex int16 Q15 interleaved [I0,Q0,I1,Q1,...]
 *     Generated by fixed build_dma_stream_dataset() — see nb_fix below.
 */
#ifndef DETECTION_H
#define DETECTION_H

#include <stdint.h>

/* ── Wideband constants ────────────────────────────────────────────────── */
#define WB_N_CHANNELS       8
#define WB_BINS_PER_CH      4096
#define WB_TOTAL_BINS       (WB_N_CHANNELS * WB_BINS_PER_CH)   /* 32768   */
#define WB_FS_PER_CH_HZ     76800000.0f
#define WB_TOTAL_BW_HZ      614400000.0f
#define WB_FREQ_RES_HZ      18750.0f        /* 76.8 MHz / 4096             */
#define WB_DMA_BYTES        131072          /* 4096 * 32 = 128 KB          */

/* ── Narrowband constants ─────────────────────────────────────────────── */
#define NB_N_POINTS         2048
#define NB_FREQ_RES_HZ      937.5f
#define NB_BW_HZ            1920000.0f      /* 2048 * 937.5 Hz = 1.92 MHz  */
#define NB_DMA_BYTES        8192            /* 2048 * 2 * 2 (int16 I+Q)    */

/* ── Result limits ────────────────────────────────────────────────────── */
#define DETECT_MAX_SIGNALS  64

/* ── DMA data types ───────────────────────────────────────────────────── */

/* WB: uint16 linear power in I, Q always 0.
 *   global_bin = ch * WB_BINS_PER_CH + local_bin */
typedef struct {
    uint16_t i[WB_N_CHANNELS];   /* linear power (noise 3-10, signal ~30000) */
    uint16_t q[WB_N_CHANNELS];   /* always 0                                 */
} WbDmaBin;                      /* sizeof = 32 bytes                        */

/* NB: int16 Q15 complex interleaved [I0,Q0,I1,Q1,...] */
typedef struct {
    int16_t iq[NB_N_POINTS * 2]; /* Q15, even=I, odd=Q                      */
} NbDmaBlock;                    /* sizeof = 8192 bytes                      */

/* ── Signal descriptor ────────────────────────────────────────────────── */
typedef struct {
    float   center_freq_hz;
    float   bandwidth_hz;
    float   power_dbfs;
    int     wb_peak_bin;
} Signal;

typedef struct {
    Signal  signals[DETECT_MAX_SIGNALS];
    int     n_signals;
} SignalList;

#endif /* DETECTION_H */
