/* inference/nn_forward.c
 * Pure-C AMCNet inference — no ONNX Runtime, no external dependencies.
 * Requires only <math.h> (expf, sqrtf).
 *
 * Network topology (input: float[3][2048]):
 *   Conv1d(3→32,k=7)  + BN + ReLU + MaxPool2
 *   Conv1d(32→64,k=5) + BN + ReLU + MaxPool2
 *   Conv1d(64→128,k=5)+ BN + ReLU + MaxPool2
 *   Conv1d(128→128,k=3)+BN + ReLU
 *   GlobalAvgPool → Linear(128→64,ReLU) → Linear(64→19) → Softmax
 */
#include "nn_forward.h"
#include "nn_weights.h"   /* generated by export_c.py */
#include <math.h>

/* ── working buffers (static: safe for bare-metal) ────────────────────── */
/* buf_a holds post-conv tensors  (max: 32×2042 = 65 344) */
/* buf_b holds post-pool tensors  (max: 32×1021 = 32 672) */
#define BUF_A 66000
#define BUF_B 33000
static float buf_a[BUF_A];
static float buf_b[BUF_B];
static float fc_vec[128];

/* ── primitives ───────────────────────────────────────────────────────── */

/* Conv1d: out[oc][t] = bias[oc] + Σ_ic Σ_k w[oc,ic,k]*in[ic,t+k] */
static void conv1d(const float *in, int in_ch, int in_len,
                   const float *w, const float *b, int out_ch, int ksize,
                   float *out)
{
    int out_len = in_len - ksize + 1;
    for (int oc = 0; oc < out_ch; oc++) {
        float *yo = out + oc * out_len;
        float  bv = b[oc];
        for (int t = 0; t < out_len; t++) {
            float s = bv;
            for (int ic = 0; ic < in_ch; ic++) {
                const float *wk = w + (oc * in_ch + ic) * ksize;
                const float *xi = in + ic * in_len + t;
                for (int k = 0; k < ksize; k++) s += wk[k] * xi[k];
            }
            yo[t] = s;
        }
    }
}

/* BatchNorm (inference, pre-folded) + ReLU in-place.
 * scale = gamma/sqrt(var+eps),  shift = beta - mean*scale  */
static void bn_relu(float *x, int ch, int len,
                    const float *scale, const float *shift)
{
    for (int c = 0; c < ch; c++) {
        float sc = scale[c], sh = shift[c];
        float *xc = x + c * len;
        for (int t = 0; t < len; t++) {
            float v = xc[t] * sc + sh;
            xc[t] = v > 0.0f ? v : 0.0f;
        }
    }
}

/* MaxPool1d stride=2 */
static void maxpool2(const float *in, int ch, int in_len, float *out)
{
    int out_len = in_len / 2;
    for (int c = 0; c < ch; c++) {
        const float *xc = in + c * in_len;
        float       *yc = out + c * out_len;
        for (int t = 0; t < out_len; t++) {
            float a = xc[2*t], b = xc[2*t+1];
            yc[t] = a > b ? a : b;
        }
    }
}

/* Global average pool: out[c] = mean over time */
static void global_avgpool(const float *in, int ch, int len, float *out)
{
    for (int c = 0; c < ch; c++) {
        const float *xc = in + c * len;
        float s = 0.0f;
        for (int t = 0; t < len; t++) s += xc[t];
        out[c] = s / (float)len;
    }
}

/* Linear + optional ReLU */
static void linear(const float *in, int in_sz,
                   const float *w, const float *b, int out_sz,
                   float *out, int relu)
{
    for (int o = 0; o < out_sz; o++) {
        const float *wo = w + o * in_sz;
        float s = b[o];
        for (int i = 0; i < in_sz; i++) s += wo[i] * in[i];
        out[o] = (relu && s < 0.0f) ? 0.0f : s;
    }
}

/* Softmax in-place */
static void softmax(float *x, int n)
{
    float mx = x[0];
    for (int i = 1; i < n; i++) if (x[i] > mx) mx = x[i];
    float s = 0.0f;
    for (int i = 0; i < n; i++) { x[i] = expf(x[i] - mx); s += x[i]; }
    for (int i = 0; i < n; i++) x[i] /= s;
}

/* ── forward pass ─────────────────────────────────────────────────────── */
int amc_forward(const float features[3][2048], float *probs_out)
{
    /* Layer 0: Conv(3→32,k=7) + BN + ReLU + MaxPool2
     *   in:  (3, 2048)   out_conv: (32, 2042)   out_pool: (32, 1021) */
    conv1d(&features[0][0], 3, 2048, L0_CONV_W, L0_CONV_B, 32, 7, buf_a);
    bn_relu(buf_a, 32, 2042, L0_BN_SCALE, L0_BN_SHIFT);
    maxpool2(buf_a, 32, 2042, buf_b);

    /* Layer 1: Conv(32→64,k=5) + BN + ReLU + MaxPool2
     *   in:  (32, 1021)  out_conv: (64, 1017)   out_pool: (64, 508)  */
    conv1d(buf_b, 32, 1021, L1_CONV_W, L1_CONV_B, 64, 5, buf_a);
    bn_relu(buf_a, 64, 1017, L1_BN_SCALE, L1_BN_SHIFT);
    maxpool2(buf_a, 64, 1017, buf_b);

    /* Layer 2: Conv(64→128,k=5) + BN + ReLU + MaxPool2
     *   in:  (64, 508)   out_conv: (128, 504)   out_pool: (128, 252) */
    conv1d(buf_b, 64, 508, L2_CONV_W, L2_CONV_B, 128, 5, buf_a);
    bn_relu(buf_a, 128, 504, L2_BN_SCALE, L2_BN_SHIFT);
    maxpool2(buf_a, 128, 504, buf_b);

    /* Layer 3: Conv(128→128,k=3) + BN + ReLU
     *   in:  (128, 252)  out_conv: (128, 250)                        */
    conv1d(buf_b, 128, 252, L3_CONV_W, L3_CONV_B, 128, 3, buf_a);
    bn_relu(buf_a, 128, 250, L3_BN_SCALE, L3_BN_SHIFT);

    /* Global average pool → (128,) */
    global_avgpool(buf_a, 128, 250, fc_vec);

    /* FC0: Linear(128→64) + ReLU */
    float fc0_out[64];
    linear(fc_vec, 128, FC0_W, FC0_B, 64, fc0_out, 1);

    /* FC1: Linear(64→19) → Softmax */
    float logits[AMC_NUM_CLASSES];
    linear(fc0_out, 64, FC1_W, FC1_B, AMC_NUM_CLASSES, logits, 0);
    softmax(logits, AMC_NUM_CLASSES);

    /* Find argmax */
    int best = 0;
    for (int i = 1; i < AMC_NUM_CLASSES; i++)
        if (logits[i] > logits[best]) best = i;

    if (probs_out)
        for (int i = 0; i < AMC_NUM_CLASSES; i++)
            probs_out[i] = logits[i];

    return best;
}
